// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/analyzer": {
    params: {};
  };
  "/ats-checker": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/job-matching": {
    params: {};
  };
  "/mock-test": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/analyzer" | "/ats-checker" | "/contact" | "/job-matching" | "/mock-test" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./analyzer/page.jsx": {
    id: "analyzer/page";
    page: "/analyzer";
  };
  "./ats-checker/page.jsx": {
    id: "ats-checker/page";
    page: "/ats-checker";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./job-matching/page.jsx": {
    id: "job-matching/page";
    page: "/job-matching";
  };
  "./mock-test/page.jsx": {
    id: "mock-test/page";
    page: "/mock-test";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "analyzer/page": typeof import("./src/app/./analyzer/page.jsx");
  "ats-checker/page": typeof import("./src/app/./ats-checker/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "job-matching/page": typeof import("./src/app/./job-matching/page.jsx");
  "mock-test/page": typeof import("./src/app/./mock-test/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};